image: python:3.7-alpine

run:
  script:
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - sphinx-build -b html doc/source/ public
  artifacts:
    paths:
    - public
  only:
  - main
